//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 11:12:29 PM EEST 
//


package lt.exchangerates.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ccy_ISO_4217.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Ccy_ISO_4217"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ADP"/&gt;
 *     &lt;enumeration value="AED"/&gt;
 *     &lt;enumeration value="AFN"/&gt;
 *     &lt;enumeration value="ALL"/&gt;
 *     &lt;enumeration value="AMD"/&gt;
 *     &lt;enumeration value="ANG"/&gt;
 *     &lt;enumeration value="AOA"/&gt;
 *     &lt;enumeration value="ARS"/&gt;
 *     &lt;enumeration value="ATS"/&gt;
 *     &lt;enumeration value="AUD"/&gt;
 *     &lt;enumeration value="AWG"/&gt;
 *     &lt;enumeration value="AZN"/&gt;
 *     &lt;enumeration value="BAM"/&gt;
 *     &lt;enumeration value="BBD"/&gt;
 *     &lt;enumeration value="BDT"/&gt;
 *     &lt;enumeration value="BEF"/&gt;
 *     &lt;enumeration value="BGN"/&gt;
 *     &lt;enumeration value="BHD"/&gt;
 *     &lt;enumeration value="BIF"/&gt;
 *     &lt;enumeration value="BYN"/&gt;
 *     &lt;enumeration value="BYR"/&gt;
 *     &lt;enumeration value="BMD"/&gt;
 *     &lt;enumeration value="BND"/&gt;
 *     &lt;enumeration value="BOB"/&gt;
 *     &lt;enumeration value="BOV"/&gt;
 *     &lt;enumeration value="BRL"/&gt;
 *     &lt;enumeration value="BSD"/&gt;
 *     &lt;enumeration value="BTN"/&gt;
 *     &lt;enumeration value="BWP"/&gt;
 *     &lt;enumeration value="BZD"/&gt;
 *     &lt;enumeration value="CAD"/&gt;
 *     &lt;enumeration value="CDF"/&gt;
 *     &lt;enumeration value="CHF"/&gt;
 *     &lt;enumeration value="CYP"/&gt;
 *     &lt;enumeration value="CLF"/&gt;
 *     &lt;enumeration value="CLP"/&gt;
 *     &lt;enumeration value="CNY"/&gt;
 *     &lt;enumeration value="COP"/&gt;
 *     &lt;enumeration value="CRC"/&gt;
 *     &lt;enumeration value="CUP"/&gt;
 *     &lt;enumeration value="CVE"/&gt;
 *     &lt;enumeration value="CZK"/&gt;
 *     &lt;enumeration value="DEM"/&gt;
 *     &lt;enumeration value="DJF"/&gt;
 *     &lt;enumeration value="DKK"/&gt;
 *     &lt;enumeration value="DOP"/&gt;
 *     &lt;enumeration value="DZD"/&gt;
 *     &lt;enumeration value="ECS"/&gt;
 *     &lt;enumeration value="ECV"/&gt;
 *     &lt;enumeration value="EEK"/&gt;
 *     &lt;enumeration value="EGP"/&gt;
 *     &lt;enumeration value="ERN"/&gt;
 *     &lt;enumeration value="ESP"/&gt;
 *     &lt;enumeration value="ETB"/&gt;
 *     &lt;enumeration value="EUR"/&gt;
 *     &lt;enumeration value="FIM"/&gt;
 *     &lt;enumeration value="FJD"/&gt;
 *     &lt;enumeration value="FKP"/&gt;
 *     &lt;enumeration value="FRF"/&gt;
 *     &lt;enumeration value="GBP"/&gt;
 *     &lt;enumeration value="GEL"/&gt;
 *     &lt;enumeration value="GHS"/&gt;
 *     &lt;enumeration value="GYD"/&gt;
 *     &lt;enumeration value="GIP"/&gt;
 *     &lt;enumeration value="GMD"/&gt;
 *     &lt;enumeration value="GNF"/&gt;
 *     &lt;enumeration value="GRD"/&gt;
 *     &lt;enumeration value="GTQ"/&gt;
 *     &lt;enumeration value="GWP"/&gt;
 *     &lt;enumeration value="HKD"/&gt;
 *     &lt;enumeration value="HNL"/&gt;
 *     &lt;enumeration value="HRK"/&gt;
 *     &lt;enumeration value="HTG"/&gt;
 *     &lt;enumeration value="HUF"/&gt;
 *     &lt;enumeration value="IDR"/&gt;
 *     &lt;enumeration value="IEP"/&gt;
 *     &lt;enumeration value="YER"/&gt;
 *     &lt;enumeration value="ILS"/&gt;
 *     &lt;enumeration value="INR"/&gt;
 *     &lt;enumeration value="IQD"/&gt;
 *     &lt;enumeration value="IRR"/&gt;
 *     &lt;enumeration value="ISK"/&gt;
 *     &lt;enumeration value="ITL"/&gt;
 *     &lt;enumeration value="JMD"/&gt;
 *     &lt;enumeration value="JOD"/&gt;
 *     &lt;enumeration value="JPY"/&gt;
 *     &lt;enumeration value="KES"/&gt;
 *     &lt;enumeration value="KGS"/&gt;
 *     &lt;enumeration value="KHR"/&gt;
 *     &lt;enumeration value="KYD"/&gt;
 *     &lt;enumeration value="KMF"/&gt;
 *     &lt;enumeration value="KPW"/&gt;
 *     &lt;enumeration value="KRW"/&gt;
 *     &lt;enumeration value="KWD"/&gt;
 *     &lt;enumeration value="KZT"/&gt;
 *     &lt;enumeration value="LAK"/&gt;
 *     &lt;enumeration value="LBP"/&gt;
 *     &lt;enumeration value="LYD"/&gt;
 *     &lt;enumeration value="LKR"/&gt;
 *     &lt;enumeration value="LRD"/&gt;
 *     &lt;enumeration value="LSL"/&gt;
 *     &lt;enumeration value="LTL"/&gt;
 *     &lt;enumeration value="LTT"/&gt;
 *     &lt;enumeration value="LUF"/&gt;
 *     &lt;enumeration value="LVL"/&gt;
 *     &lt;enumeration value="MAD"/&gt;
 *     &lt;enumeration value="MDL"/&gt;
 *     &lt;enumeration value="MDR"/&gt;
 *     &lt;enumeration value="MGA"/&gt;
 *     &lt;enumeration value="MYR"/&gt;
 *     &lt;enumeration value="MKD"/&gt;
 *     &lt;enumeration value="MMK"/&gt;
 *     &lt;enumeration value="MNT"/&gt;
 *     &lt;enumeration value="MOP"/&gt;
 *     &lt;enumeration value="MRO"/&gt;
 *     &lt;enumeration value="MTL"/&gt;
 *     &lt;enumeration value="MUR"/&gt;
 *     &lt;enumeration value="MVR"/&gt;
 *     &lt;enumeration value="MWK"/&gt;
 *     &lt;enumeration value="MXN"/&gt;
 *     &lt;enumeration value="MXV"/&gt;
 *     &lt;enumeration value="MZN"/&gt;
 *     &lt;enumeration value="NAD"/&gt;
 *     &lt;enumeration value="NGN"/&gt;
 *     &lt;enumeration value="NIO"/&gt;
 *     &lt;enumeration value="NLG"/&gt;
 *     &lt;enumeration value="NOK"/&gt;
 *     &lt;enumeration value="NPR"/&gt;
 *     &lt;enumeration value="NZD"/&gt;
 *     &lt;enumeration value="OMR"/&gt;
 *     &lt;enumeration value="PAB"/&gt;
 *     &lt;enumeration value="PEN"/&gt;
 *     &lt;enumeration value="PGK"/&gt;
 *     &lt;enumeration value="PHP"/&gt;
 *     &lt;enumeration value="PYG"/&gt;
 *     &lt;enumeration value="PKR"/&gt;
 *     &lt;enumeration value="PLN"/&gt;
 *     &lt;enumeration value="PTE"/&gt;
 *     &lt;enumeration value="QAR"/&gt;
 *     &lt;enumeration value="RON"/&gt;
 *     &lt;enumeration value="RSD"/&gt;
 *     &lt;enumeration value="RUB"/&gt;
 *     &lt;enumeration value="RWF"/&gt;
 *     &lt;enumeration value="SAR"/&gt;
 *     &lt;enumeration value="SBD"/&gt;
 *     &lt;enumeration value="SCR"/&gt;
 *     &lt;enumeration value="SDD"/&gt;
 *     &lt;enumeration value="SEK"/&gt;
 *     &lt;enumeration value="SGD"/&gt;
 *     &lt;enumeration value="SHP"/&gt;
 *     &lt;enumeration value="SYP"/&gt;
 *     &lt;enumeration value="SIT"/&gt;
 *     &lt;enumeration value="SKK"/&gt;
 *     &lt;enumeration value="SLL"/&gt;
 *     &lt;enumeration value="SOS"/&gt;
 *     &lt;enumeration value="SRD"/&gt;
 *     &lt;enumeration value="SSP"/&gt;
 *     &lt;enumeration value="STD"/&gt;
 *     &lt;enumeration value="SVC"/&gt;
 *     &lt;enumeration value="SZL"/&gt;
 *     &lt;enumeration value="THB"/&gt;
 *     &lt;enumeration value="TJR"/&gt;
 *     &lt;enumeration value="TJS"/&gt;
 *     &lt;enumeration value="TMT"/&gt;
 *     &lt;enumeration value="TND"/&gt;
 *     &lt;enumeration value="TOP"/&gt;
 *     &lt;enumeration value="TPE"/&gt;
 *     &lt;enumeration value="TRY"/&gt;
 *     &lt;enumeration value="TTD"/&gt;
 *     &lt;enumeration value="TWD"/&gt;
 *     &lt;enumeration value="TZS"/&gt;
 *     &lt;enumeration value="UAH"/&gt;
 *     &lt;enumeration value="UGX"/&gt;
 *     &lt;enumeration value="UYU"/&gt;
 *     &lt;enumeration value="USD"/&gt;
 *     &lt;enumeration value="USN"/&gt;
 *     &lt;enumeration value="UZS"/&gt;
 *     &lt;enumeration value="VEB"/&gt;
 *     &lt;enumeration value="VES"/&gt;
 *     &lt;enumeration value="VND"/&gt;
 *     &lt;enumeration value="VUV"/&gt;
 *     &lt;enumeration value="WST"/&gt;
 *     &lt;enumeration value="XAF"/&gt;
 *     &lt;enumeration value="XAG"/&gt;
 *     &lt;enumeration value="XAU"/&gt;
 *     &lt;enumeration value="XBA"/&gt;
 *     &lt;enumeration value="XBB"/&gt;
 *     &lt;enumeration value="XBC"/&gt;
 *     &lt;enumeration value="XBD"/&gt;
 *     &lt;enumeration value="XCD"/&gt;
 *     &lt;enumeration value="XDR"/&gt;
 *     &lt;enumeration value="XFO"/&gt;
 *     &lt;enumeration value="XFU"/&gt;
 *     &lt;enumeration value="XOF"/&gt;
 *     &lt;enumeration value="XPD"/&gt;
 *     &lt;enumeration value="XPF"/&gt;
 *     &lt;enumeration value="XPT"/&gt;
 *     &lt;enumeration value="XXX"/&gt;
 *     &lt;enumeration value="ZAR"/&gt;
 *     &lt;enumeration value="ZMW"/&gt;
 *     &lt;enumeration value="ZRN"/&gt;
 *     &lt;enumeration value="ZWL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "Ccy_ISO_4217")
@XmlEnum
public enum CcyISO4217 {


    /**
     * Andorran peseta
     * 
     */
    ADP,

    /**
     * UAE dirham
     * 
     */
    AED,

    /**
     * Afghani
     * 
     */
    AFN,

    /**
     * Albanian lek
     * 
     */
    ALL,

    /**
     * Armenian dram
     * 
     */
    AMD,

    /**
     * Netherlands Antillean guilder
     * 
     */
    ANG,

    /**
     * Kwanza
     * 
     */
    AOA,

    /**
     * Argentine peso
     * 
     */
    ARS,

    /**
     * Austrian schilling
     * 
     */
    ATS,

    /**
     * Australian dollar
     * 
     */
    AUD,

    /**
     * Aruban florin
     * 
     */
    AWG,

    /**
     * Azerbaijan manat
     * 
     */
    AZN,

    /**
     * Convertible marks
     * 
     */
    BAM,

    /**
     * Barbodos dollar
     * 
     */
    BBD,

    /**
     * Bangladeshi taka
     * 
     */
    BDT,

    /**
     * Belgian franc
     * 
     */
    BEF,

    /**
     * Bulgarian lev
     * 
     */
    BGN,

    /**
     * Bahraini dinar
     * 
     */
    BHD,

    /**
     * Burundi franc
     * 
     */
    BIF,

    /**
     * Belarusian ruble
     * 
     */
    BYN,

    /**
     * Belarusian ruble
     * 
     */
    BYR,

    /**
     * Bermudian dollar
     * 
     */
    BMD,

    /**
     * Brunei dollar
     * 
     */
    BND,

    /**
     * Bolivian boliviano
     * 
     */
    BOB,

    /**
     * Mvdol
     * 
     */
    BOV,

    /**
     * Brazilian real
     * 
     */
    BRL,

    /**
     * Bahamian dollar
     * 
     */
    BSD,

    /**
     * Ngultrum
     * 
     */
    BTN,

    /**
     * Pula
     * 
     */
    BWP,

    /**
     * Belize dollar
     * 
     */
    BZD,

    /**
     * Canadian dollar
     * 
     */
    CAD,

    /**
     * Congolese Franc
     * 
     */
    CDF,

    /**
     * Swiss franc
     * 
     */
    CHF,

    /**
     * Cyprus pound
     * 
     */
    CYP,

    /**
     * Unidad de fomento
     * 
     */
    CLF,

    /**
     * Chilean peso
     * 
     */
    CLP,

    /**
     * Chinese yuan renminbi
     * 
     */
    CNY,

    /**
     * Colombian peso
     * 
     */
    COP,

    /**
     * Costa Rican colon
     * 
     */
    CRC,

    /**
     * Cuban peso
     * 
     */
    CUP,

    /**
     * Cape Verde escudo
     * 
     */
    CVE,

    /**
     * Czech koruna
     * 
     */
    CZK,

    /**
     * Deutsche mark
     * 
     */
    DEM,

    /**
     * Djibouti franc
     * 
     */
    DJF,

    /**
     * Danish krone
     * 
     */
    DKK,

    /**
     * Dominican peso
     * 
     */
    DOP,

    /**
     * Algerian dinar
     * 
     */
    DZD,

    /**
     * Ecuadoran sucre
     * 
     */
    ECS,

    /**
     * Unidad de valor
     * 
     */
    ECV,

    /**
     * Estonian kroon
     * 
     */
    EEK,

    /**
     * Egyptian pound
     * 
     */
    EGP,

    /**
     * Nakfa
     * 
     */
    ERN,

    /**
     * Spanish peseta
     * 
     */
    ESP,

    /**
     * Ethiopian birr
     * 
     */
    ETB,

    /**
     * Euro
     * 
     */
    EUR,

    /**
     * Finnish markka
     * 
     */
    FIM,

    /**
     * Fiji dollar
     * 
     */
    FJD,

    /**
     * Falkland islands pound
     * 
     */
    FKP,

    /**
     * French franc
     * 
     */
    FRF,

    /**
     * Pound sterling
     * 
     */
    GBP,

    /**
     * Georgian lari
     * 
     */
    GEL,

    /**
     * Ghana cedi
     * 
     */
    GHS,

    /**
     * Guyana dollar
     * 
     */
    GYD,

    /**
     * Gibraltar pound
     * 
     */
    GIP,

    /**
     * Dalasi
     * 
     */
    GMD,

    /**
     * Guinean franc
     * 
     */
    GNF,

    /**
     * Greek drachma
     * 
     */
    GRD,

    /**
     * Quetzal
     * 
     */
    GTQ,

    /**
     * Guinea-Bissau peso
     * 
     */
    GWP,

    /**
     * Hong Kong dollar
     * 
     */
    HKD,

    /**
     * Lempira
     * 
     */
    HNL,

    /**
     * Croatian kuna
     * 
     */
    HRK,

    /**
     * Gourde
     * 
     */
    HTG,

    /**
     * Hungarian forint
     * 
     */
    HUF,

    /**
     * Indonesian rupiah
     * 
     */
    IDR,

    /**
     * Irish pound
     * 
     */
    IEP,

    /**
     * Yemeni rial
     * 
     */
    YER,

    /**
     * Israeli new shekel
     * 
     */
    ILS,

    /**
     * Indian rupee
     * 
     */
    INR,

    /**
     * Iraqi dinar
     * 
     */
    IQD,

    /**
     * Iranian rial
     * 
     */
    IRR,

    /**
     * Iceland krona
     * 
     */
    ISK,

    /**
     * Italian lire
     * 
     */
    ITL,

    /**
     * Jamaican dollar
     * 
     */
    JMD,

    /**
     * Jordanian dinar
     * 
     */
    JOD,

    /**
     * Japanese yen
     * 
     */
    JPY,

    /**
     * Kenyan shilling
     * 
     */
    KES,

    /**
     * Kyrghyzstan som
     * 
     */
    KGS,

    /**
     * Riel
     * 
     */
    KHR,

    /**
     * Cayman islands dollar
     * 
     */
    KYD,

    /**
     * Comorian franc
     * 
     */
    KMF,

    /**
     * North Korean won
     * 
     */
    KPW,

    /**
     * South Korean won
     * 
     */
    KRW,

    /**
     * Kuwaiti dinar
     * 
     */
    KWD,

    /**
     * Kazakhstan tenge
     * 
     */
    KZT,

    /**
     * Lao kip
     * 
     */
    LAK,

    /**
     * Lebanese pound
     * 
     */
    LBP,

    /**
     * Libyan dinar
     * 
     */
    LYD,

    /**
     * Sri Lanka rupee
     * 
     */
    LKR,

    /**
     * Liberian dollar
     * 
     */
    LRD,

    /**
     * Loti
     * 
     */
    LSL,

    /**
     * Lithuanian litas
     * 
     */
    LTL,

    /**
     * Lithuanian talonas
     * 
     */
    LTT,

    /**
     * Luxembourg franc
     * 
     */
    LUF,

    /**
     * Latvian lats
     * 
     */
    LVL,

    /**
     * Moroccan dirham
     * 
     */
    MAD,

    /**
     * Moldovan leu
     * 
     */
    MDL,

    /**
     * Moldovan ruble
     * 
     */
    MDR,

    /**
     * Malagasy ariary
     * 
     */
    MGA,

    /**
     * Malaysian ringgit
     * 
     */
    MYR,

    /**
     * Macedonian denar
     * 
     */
    MKD,

    /**
     * Kyat
     * 
     */
    MMK,

    /**
     * Mongolian tugrik
     * 
     */
    MNT,

    /**
     * Pataca
     * 
     */
    MOP,

    /**
     * Ouguiya
     * 
     */
    MRO,

    /**
     * Maltese lira
     * 
     */
    MTL,

    /**
     * Mauritius rupee
     * 
     */
    MUR,

    /**
     * Rufiyaa
     * 
     */
    MVR,

    /**
     * Malawi kwacha
     * 
     */
    MWK,

    /**
     * Mexican peso
     * 
     */
    MXN,

    /**
     * Mexican unidad de inversion (UDI)
     * 
     */
    MXV,

    /**
     * Mozambique metical
     * 
     */
    MZN,

    /**
     * Namibia dollar
     * 
     */
    NAD,

    /**
     * Naira
     * 
     */
    NGN,

    /**
     * Cordoba oro
     * 
     */
    NIO,

    /**
     * Netherlands guilder
     * 
     */
    NLG,

    /**
     * Norwegian krone
     * 
     */
    NOK,

    /**
     * Nepalese rupee
     * 
     */
    NPR,

    /**
     * New Zealand dollar
     * 
     */
    NZD,

    /**
     * Rial Omani
     * 
     */
    OMR,

    /**
     * Panamanian balboa
     * 
     */
    PAB,

    /**
     * Peruvian sol
     * 
     */
    PEN,

    /**
     * Kina
     * 
     */
    PGK,

    /**
     * Philippine peso
     * 
     */
    PHP,

    /**
     * Guarani
     * 
     */
    PYG,

    /**
     * Pakistan rupee
     * 
     */
    PKR,

    /**
     * Polish zloty
     * 
     */
    PLN,

    /**
     * Portuguese escudo
     * 
     */
    PTE,

    /**
     * Qatari rial
     * 
     */
    QAR,

    /**
     * Romanian leu
     * 
     */
    RON,

    /**
     * Serbian dinar
     * 
     */
    RSD,

    /**
     * Russian ruble
     * 
     */
    RUB,

    /**
     * Rwanda franc
     * 
     */
    RWF,

    /**
     * Saudi riyal
     * 
     */
    SAR,

    /**
     * Solomon islands dollar
     * 
     */
    SBD,

    /**
     * Seychelles rupee
     * 
     */
    SCR,

    /**
     * Sudanese dinar
     * 
     */
    SDD,

    /**
     * Swedish krona
     * 
     */
    SEK,

    /**
     * Singapore dollar
     * 
     */
    SGD,

    /**
     * St.Helena pound
     * 
     */
    SHP,

    /**
     * Syrian pound
     * 
     */
    SYP,

    /**
     * Slovenian tolar
     * 
     */
    SIT,

    /**
     * Slovak koruna
     * 
     */
    SKK,

    /**
     * Leone
     * 
     */
    SLL,

    /**
     * Somali shilling
     * 
     */
    SOS,

    /**
     * Suriname dollar
     * 
     */
    SRD,

    /**
     * South Sudanese pound
     * 
     */
    SSP,

    /**
     * Dobra
     * 
     */
    STD,

    /**
     * El Salvador colon
     * 
     */
    SVC,

    /**
     * Lilangeni
     * 
     */
    SZL,

    /**
     * Thai baht
     * 
     */
    THB,

    /**
     * Tajik ruble
     * 
     */
    TJR,

    /**
     * Tajikistan somoni
     * 
     */
    TJS,

    /**
     * Turkmenistan new manat
     * 
     */
    TMT,

    /**
     * Tunisian dinar
     * 
     */
    TND,

    /**
     * Pa'anga
     * 
     */
    TOP,

    /**
     * Timor escudo
     * 
     */
    TPE,

    /**
     * Turkish lira
     * 
     */
    TRY,

    /**
     * Trinidad and Tobago dollar
     * 
     */
    TTD,

    /**
     * Taiwan new dollar
     * 
     */
    TWD,

    /**
     * Tanzanian shilling
     * 
     */
    TZS,

    /**
     * Ukrainian hryvnia
     * 
     */
    UAH,

    /**
     * Uganda shilling
     * 
     */
    UGX,

    /**
     * Peso Uruguayo
     * 
     */
    UYU,

    /**
     * US dollar
     * 
     */
    USD,

    /**
     * US dollar (Next day)
     * 
     */
    USN,

    /**
     * Uzbekistan sum
     * 
     */
    UZS,

    /**
     * Venezuelan bolivar
     * 
     */
    VEB,

    /**
     * Venezuelan bolivar soberano
     * 
     */
    VES,

    /**
     * Vietnamese dong
     * 
     */
    VND,

    /**
     * Vatu
     * 
     */
    VUV,

    /**
     * Tala
     * 
     */
    WST,

    /**
     * CFA franc BEAC
     * 
     */
    XAF,

    /**
     * Silver
     * 
     */
    XAG,

    /**
     * Gold
     * 
     */
    XAU,

    /**
     * European composite unit (EURCO)
     * 
     */
    XBA,

    /**
     * European monetary unit (EMU-6)
     * 
     */
    XBB,

    /**
     * European unit of account-9 (EUA-9)
     * 
     */
    XBC,

    /**
     * European unit of account-17 (EUA-17)
     * 
     */
    XBD,

    /**
     * East Karibbean dollar
     * 
     */
    XCD,

    /**
     * SDR I.M.F.
     * 
     */
    XDR,

    /**
     * Gold-franc (special settlement currency)
     * 
     */
    XFO,

    /**
     * Uic-franc (special settlement currency)
     * 
     */
    XFU,

    /**
     * CFA franc BCEAO
     * 
     */
    XOF,

    /**
     * Palladium
     * 
     */
    XPD,

    /**
     * CFP franc
     * 
     */
    XPF,

    /**
     * Platinum
     * 
     */
    XPT,

    /**
     * Transactions without currency
     * 
     */
    XXX,

    /**
     * South African rand
     * 
     */
    ZAR,

    /**
     * Zambian Kwacha
     * 
     */
    ZMW,

    /**
     * New zaire
     * 
     */
    ZRN,

    /**
     * Zimbabwe dollar
     * 
     */
    ZWL;

    public String value() {
        return name();
    }

    public static CcyISO4217 fromValue(String v) {
        return valueOf(v);
    }

}
