//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 12:06:23 AM EEST 
//


package lt.exchangerates.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of foreign exchange rates or technical error report
 * 
 * <p>Java class for FxRatesHandling complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FxRatesHandling"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="FxRate" type="{http://www.lb.lt/WebServices/FxRates}FxRateHandling" maxOccurs="unbounded"/&gt;
 *           &lt;element name="OprlErr" type="{http://www.lb.lt/WebServices/FxRates}OprlErrHandling"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FxRatesHandling", propOrder = {
    "fxRate",
    "oprlErr"
})
public class FxRatesHandling {

    @XmlElement(name = "FxRate")
    protected List<FxRateHandling> fxRate;
    @XmlElement(name = "OprlErr")
    protected OprlErrHandling oprlErr;

    /**
     * Gets the value of the fxRate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fxRate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFxRate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FxRateHandling }
     * 
     * 
     */
    public List<FxRateHandling> getFxRate() {
        if (fxRate == null) {
            fxRate = new ArrayList<FxRateHandling>();
        }
        return this.fxRate;
    }

    /**
     * Gets the value of the oprlErr property.
     * 
     * @return
     *     possible object is
     *     {@link OprlErrHandling }
     *     
     */
    public OprlErrHandling getOprlErr() {
        return oprlErr;
    }

    /**
     * Sets the value of the oprlErr property.
     * 
     * @param value
     *     allowed object is
     *     {@link OprlErrHandling }
     *     
     */
    public void setOprlErr(OprlErrHandling value) {
        this.oprlErr = value;
    }

}
