//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.03 at 11:12:29 PM EEST 
//


package lt.exchangerates.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the lt.exchangerates.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FxRates_QNAME = new QName("http://www.lb.lt/WebServices/FxRates", "FxRates");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: lt.exchangerates.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FxRatesHandling }
     * 
     */
    public FxRatesHandling createFxRatesHandling() {
        return new FxRatesHandling();
    }

    /**
     * Create an instance of {@link FxRateHandling }
     * 
     */
    public FxRateHandling createFxRateHandling() {
        return new FxRateHandling();
    }

    /**
     * Create an instance of {@link CcyAmtHandling }
     * 
     */
    public CcyAmtHandling createCcyAmtHandling() {
        return new CcyAmtHandling();
    }

    /**
     * Create an instance of {@link OprlErrHandling }
     * 
     */
    public OprlErrHandling createOprlErrHandling() {
        return new OprlErrHandling();
    }

    /**
     * Create an instance of {@link ErrorCode }
     * 
     */
    public ErrorCode createErrorCode() {
        return new ErrorCode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FxRatesHandling }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FxRatesHandling }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.lb.lt/WebServices/FxRates", name = "FxRates")
    public JAXBElement<FxRatesHandling> createFxRates(FxRatesHandling value) {
        return new JAXBElement<FxRatesHandling>(_FxRates_QNAME, FxRatesHandling.class, null, value);
    }

}
